### ISSUE TITLE
code suggestion 

### ISSUE THREAD

**Issue by Tetrax-10** [Aztup/EnhancePlus#1]
Thanks for this awesome extension ❤️, really useful and i love it !

Just a small suggestion for this part of the code 
![image](https://user-images.githubusercontent.com/75513645/205290435-2c7747c2-e78a-43ee-88ba-14a3dbb640a2.png)

There is a built in listner to detect song change
```js
Spicetify.Player.addEventListener("songchange", functionName);
```
This [docs](https://github.com/spicetify/spicetify-cli/blob/master/globals.d.ts) will be useful for you 🤗

also follow the naming convention
![image](https://user-images.githubusercontent.com/75513645/205297082-33c8b0eb-92eb-40f0-9ca3-e89fb8458883.png)

**Comment by Aztup** [comment]
Thanks for the tip I think I fixed everything in the latest commit

**Comment by Tetrax-10** [comment]
can i ask why you use this part? even after implementing listner.
`onSongChanged()` will only get triggred when there is a diff song played

**Comment by Aztup** [comment]
Cause if you re-start spotify and had an enhanced song playing it will not add the buttons back until you switch song I just tested.

**Comment by Tetrax-10** [comment]
Can you add a context menu to play only the enhanced songs in a enhanced playlist. I always wanted this feature so i dont want to manually skip the old songs. It will be better to add the filtered songs to the queue like shuffle+ and sort by playcount extensions. thx
![image](https://user-images.githubusercontent.com/75513645/205507620-d996bdaf-1b2b-42fc-acf3-f728eb561397.png)

**Comment by Tetrax-10** [comment]
Can you add a option to skip non-enhanced songs similar to this [extension](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Skip-or-Play-Liked-Songs)
![image](https://user-images.githubusercontent.com/75513645/205894444-3a428153-a084-45ae-8371-a5919fc59164.png)

this can be easly implemented by adding this code to else part
```js
Spicetify.Player.next();
```
![image](https://user-images.githubusercontent.com/75513645/205894848-c329bef0-1cc8-43cd-9685-c44486f6e068.png)
