### ISSUE TITLE
Works for one song, then disappears

### ISSUE THREAD

**Issue by mkwiimaster7** [Aztup/EnhancePlus#3]
title. edit: it looks like Enhanced + is incompatible with Play Enhanced Songs extension

**Comment by mkwiimaster7** [comment]
Also the buttons dont actually remove the song from the playlist or remove it from the playlist

**Comment by Aztup** [comment]
Should be fixed on latest version can you confirm?

**Comment by mkwiimaster7** [comment]
Yes it worked, thank you!
